//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int logsId { get; set; }
        public string logsMessage { get; set; }
        public string logsPath { get; set; }
        public Nullable<System.DateTime> logsData { get; set; }
    }
}
